/* This is an automatically generated file */

static char* pref_init_buffer = 
"/* -*- Mode: Java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-\n"
" *\n"
" * The contents of this file are subject to the Netscape Public License\n"
" * Version 1.0 (the \"NPL\"); you may not use this file except in\n"
" * compliance with the NPL.  You may obtain a copy of the NPL at\n"
" * http://www.mozilla.org/NPL/\n"
" *\n"
" * Software distributed under the NPL is distributed on an \"AS IS\" basis,\n"
" * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL\n"
" * for the specific language governing rights and limitations under the\n"
" * NPL.\n"
" *\n"
" * The Initial Developer of this code under the NPL is Netscape\n"
" * Communications Corporation.  Portions created by Netscape are\n"
" * Copyright (C) 1998 Netscape Communications Corporation.  All Rights\n"
" * Reserved.\n"
" */\n"
"\n"
"// Style note 3/3:\n"
"// internal objects & functions are in under_score form.\n"
"// public functions are in interCaps.\n"
"\n"
"// Remove this -- but called in winpref.js :\n"
"// platform.windows = true;\n"
"function plat() {\n"
"    this.windows=false;\n"
"    this.mac=false;\n"
"    this.unix=false;\n"
"};\n"
"platform = new plat();\n"
"\n"
"/* --- Preference initialization functions ---\n"
"\n"
"    Moved to native functions:\n"
"    pref        -> pref_NativeDefaultPref\n"
"    defaultPref -> \"\n"
"    userPref    -> pref_NativeUserPref\n"
"    lockPref    -> pref_NativeLockPref\n"
"    unlockPref  -> pref_NativeUnlockPref\n"
"    getPref     -> pref_NativeGetPref\n"
"    config      -> pref_NativeDefaultPref   (?)\n"
"*/\n"
"\n"
"// stubs for compatability\n"
"var default_pref = defaultPref;\n"
"var lock_pref = lockPref;\n"
"var unlock_pref = unlockPref;\n"
"var userPref = user_pref;\n"
"\n"
"// -------------------------\n"
"\n"
"function mime_type(root, mimetype, extension, load_action, appname, appsig, filetype)\n"
"{\n"
"    // changed for prefbert\n"
"    pref(root + \".mimetype\", mimetype);\n"
"    pref(root + \".extension\", extension);\n"
"    pref(root + \".load_action\", load_action);\n"
"    pref(root + \".mac_appname\", appname);\n"
"    pref(root + \".mac_appsig\", appsig);\n"
"    pref(root + \".mac_filetype\", filetype);\n"
"    pref(root + \".description\", \"\");\n"
"    pref(root + \".latent_plug_in\", false);\n"
"}\n"
"\n"
"// LDAP\n"
"// Searches for \"key=value\" in the given string and returns value.\n"
"function getLDAPValue(str, key)\n"
"{\n"
"    if (str == null || key == null)\n"
"        return null;\n"
"\n"
"    var search_key = \"\\n\" + key + \"=\";\n"
"\n"
"    var start_pos = str.indexOf(search_key);\n"
"    if (start_pos == -1)\n"
"        return null;\n"
"\n"
"    start_pos += search_key.length;\n"
"\n"
"    var end_pos = str.indexOf(\"\\n\", start_pos);\n"
"    if (end_pos == -1)\n"
"        end_pos = str.length;\n"
"\n"
"    return str.substring(start_pos, end_pos);\n"
"}\n"
"\n"
"function begin_mime_def()\n"
"{\n"
"}\n"
"\n"
"function end_mime_def()\n"
"{\n"
"   var now = new Date();\n"
"   pref(\"mime.types.all_defined\", now.toString());\n"
"}\n"
"\n"
"/* -*- Mode: Java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-\n"
" *\n"
" * The contents of this file are subject to the Netscape Public License\n"
" * Version 1.0 (the \"NPL\"); you may not use this file except in\n"
" * compliance with the NPL.  You may obtain a copy of the NPL at\n"
" * http://www.mozilla.org/NPL/\n"
" *\n"
" * Software distributed under the NPL is distributed on an \"AS IS\" basis,\n"
" * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL\n"
" * for the specific language governing rights and limitations under the\n"
" * NPL.\n"
" *\n"
" * The Initial Developer of this code under the NPL is Netscape\n"
" * Communications Corporation.  Portions created by Netscape are\n"
" * Copyright (C) 1998 Netscape Communications Corporation.  All Rights\n"
" * Reserved.\n"
" */\n"
"\n"
"// SYNTAX HINTS:  dashes are delimiters.  Use underscores instead.\n"
"//  The first character after a period must be alphabetic.\n"
"\n"
"config(\"timebomb.expiration_time\",-1);\n"
"config(\"timebomb.warning_time\",-1);\n"
"config(\"timebomb.relative_timebomb_secret_name\",\"general.bproxy_cert_digest\");\n"
"config(\"timebomb.relative_timebomb_days\",-1);\n"
"config(\"timebomb.relative_timebomb_warning_days\",-1);\n"
"\n"
"pref(\"network.search.url\",\"http://cgi.netscape.com/cgi-bin/url_search.cgi?search=\");\n"
"pref(\"general.bproxy_cert_digest\",0);\n"
"\n"
"pref(\"general.startup.browser\",             true);\n"
"pref(\"general.startup.mail\",                false);\n"
"pref(\"general.startup.news\",                false);\n"
"pref(\"general.startup.editor\",              false);\n"
"pref(\"general.startup.conference\",          false);\n"
"pref(\"general.startup.calendar\",            false);\n"
"pref(\"general.startup.netcaster\",           false);\n"
"\n"
"pref(\"general.always_load_images\",          true);\n"
"pref(\"general.always_load_movies\",          true);\n"
"pref(\"general.always_load_sounds\",          true);\n"
"pref(\"general.title_tips\",                  true);\n"
"\n"
"pref(\"general.help_source.site\",            1); // 0 = Netscape, 1 = installed, 2 = custom\n"
"pref(\"general.help_source.url\",             \"\");\n"
"\n"
"pref(\"general.fullcircle_enable\",           true);\n"
"pref(\"general.fullcircle_collect_ns_data\",  false);\n"
"\n"
"pref(\"browser.enable_style_sheets\",         true);\n"
"pref(\"browser.startup.page\",                1);     // 0 = blank, 1 = home, 2 = last\n"
"pref(\"browser.startup.homepage\",            \"http://www.mozilla.org/\");\n"
"pref(\"browser.startup.homepage_override\",   true);\n"
"pref(\"browser.startup.autoload_homepage\",   true);\n"
"pref(\"browser.startup.agreed_to_licence\",   false);\n"
"pref(\"browser.startup.license_version\",     0);\n"
"pref(\"browser.startup.default_window\",      1); // start up browser\n"
"pref(\"browser.cache.disk_cache_size\",       7680);\n"
"pref(\"browser.cache.memory_cache_size\",     1024);\n"
"pref(\"browser.cache.disk_cache_ssl\",        false);\n"
"pref(\"browser.foreground_color\",            \"#000000\");\n"
"pref(\"browser.background_color\",            \"#C0C0C0\");\n"
"pref(\"browser.anchor_color\",                \"#0000EE\");\n"
"pref(\"browser.visited_color\",               \"#551A8B\");\n"
"pref(\"browser.chrome.show_directory_buttons\",   true);\n"
"pref(\"browser.chrome.toolbar_style\",        2);\n"
"pref(\"browser.chrome.advanced_toolbar\",     false);\n"
"pref(\"browser.chrome.show_toolbar\",         true);\n"
"pref(\"browser.chrome.show_status_bar\",      true);\n"
"pref(\"browser.chrome.show_url_bar\",         true);\n"
"pref(\"browser.chrome.show_security_bar\",    true);\n"
"pref(\"browser.chrome.button_style\",         0);\n"
"\n"
"pref(\"browser.background_option\",           0); // DEFAULT_BACKGROUND\n"
"pref(\"browser.link_expiration\",             9);\n"
"pref(\"browser.cache.check_doc_frequency\",   0);\n"
"\n"
"pref(\"browser.delay_images\",                false);\n"
"pref(\"browser.underline_anchors\",           true);\n"
"pref(\"browser.never_expire\",                false);\n"
"pref(\"browser.display_while_loading\",       true);\n"
"pref(\"browser.custom_link_color\",           false);\n"
"pref(\"browser.custom_visited_color\",        false);\n"
"pref(\"browser.custom_text_color\",           false);\n"
"pref(\"browser.use_document_colors\",         true);\n"
"pref(\"browser.ldapfile_location\",       \"\");\n"
"pref(\"browser.print_background\",            false);\n"
"pref(\"browser.prefs_window_rect\",           \"-1,-1,-1,-1\");\n"
"pref(\"browser.find_window_rect\",            \"-1,-1,-1,-1\");\n"
"pref(\"browser.bookmark_window_rect\",        \"-1,-1,-1,-1\");\n"
"pref(\"browser.download_window_rect\",        \"-1,-1,-1,-1\");\n"
"pref(\"browser.wfe.ignore_def_check\",false);\n"
"pref(\"browser.wfe.use_windows_colors\",true);\n"
"pref(\"browser.startup_mode\",1);\n"
"localDefPref(\"browser.bookmark_location\",       \"\");\n"
"localDefPref(\"browser.addressbook_location\",    \"\");\n"
"localDefPref(\"browser.socksfile_location\",      \"\");\n"
"localDefPref(\"browser.ldapfile_location\",       \"\");\n"
"\n"
"pref(\"browser.url_history.URL_1\", \"\");\n"
"pref(\"browser.url_history.URL_2\", \"\");\n"
"pref(\"browser.url_history.URL_3\", \"\");\n"
"pref(\"browser.url_history.URL_4\", \"\");\n"
"pref(\"browser.url_history.URL_5\", \"\");\n"
"pref(\"browser.url_history.URL_6\", \"\");\n"
"pref(\"browser.url_history.URL_7\", \"\");\n"
"pref(\"browser.url_history.URL_8\", \"\");\n"
"pref(\"browser.url_history.URL_9\", \"\");\n"
"pref(\"browser.url_history.URL_10\", \"\");\n"
"pref(\"browser.url_history.URL_11\", \"\");\n"
"pref(\"browser.url_history.URL_12\", \"\");\n"
"pref(\"browser.url_history.URL_13\", \"\");\n"
"pref(\"browser.url_history.URL_14\", \"\");\n"
"pref(\"browser.url_history.URL_15\", \"\");\n"
"\n"
"pref(\"browser.personal_toolbar_button.min_chars\", 15);\n"
"pref(\"browser.personal_toolbar_button.max_chars\", 30);\n"
"\n"
"pref(\"browser.PICS.ratings_enabled\", false);\n"
"pref(\"browser.PICS.pages_must_be_rated\", false);\n"
"pref(\"browser.PICS.disable_for_this_session\", false);\n"
"pref(\"browser.PICS.reenable_for_this_session\", false);\n"
"pref(\"browser.PICS.service.http___home_netscape_com_default_rating.service_enabled\", true);\n"
"pref(\"browser.PICS.service.http___home_netscape_com_default_rating.s\", 0);\n"
"\n"
"\n"
"// Smart Browsing prefs\n"
"pref(\"browser.related.enabled\", true);\n"
"pref(\"browser.related.autoload\", 1);  // 0 = Always, 1 = After first use, 2 = Never\n"
"pref(\"browser.related.provider\", \"http://www-rl.netscape.com/wtgn?\");\n"
"pref(\"browser.related.detailsProvider\", \"http://cgi.netscape.com/cgi-bin/rlcgi.cgi?URL=\");\n"
"pref(\"browser.related.disabledForDomains\", \"\");\n"
"pref(\"browser.goBrowsing.enabled\", true);\n"
"\n"
"\n"
"// The NavCenter preferences\n"
"localDefPref(\"browser.navcenter.dockstyle\", 1); // 1 = left, 2 = right, 3 = top, 4 = bottom\n"
"localDefPref(\"browser.navcenter.docked.tree.visible\", false);\n"
"localDefPref(\"browser.navcenter.docked.selector.visible\", true);\n"
"localDefPref(\"browser.navcenter.docked.tree.width\", 250); // Percent of parent window consumed by docked nav center\n"
"localDefPref(\"browser.navcenter.floating.rect\", \"20, 20, 400, 600\"); // Window dimensions when floating\n"
"\n"
"localDefPref(\"ghist.expires.pos\",          4);\n"
"localDefPref(\"ghist.expires.width\",        1400);\n"
"localDefPref(\"ghist.firstvisit.pos\",       2);\n"
"localDefPref(\"ghist.firstvisit.width\",     1400);\n"
"localDefPref(\"ghist.lastvisit.pos\",        3);\n"
"localDefPref(\"ghist.lastvisit.width\",      1400);\n"
"localDefPref(\"ghist.location.pos\",         1);\n"
"localDefPref(\"ghist.location.width\",       2400);\n"
"pref(\"ghist.show_value\",           0);\n"
"pref(\"ghist.sort_descending\",      false);\n"
"pref(\"ghist.sortby\",               3);  // eGH_LastDateSort\n"
"localDefPref(\"ghist.title.pos\",            0);\n"
"localDefPref(\"ghist.title.width\",          2400);\n"
"localDefPref(\"ghist.visiblecolumns\",       6);\n"
"localDefPref(\"ghist.visitcount.pos\",       5);\n"
"localDefPref(\"ghist.visitcount.width\",     1000);\n"
"localDefPref(\"ghist.window_rect\",          \"0,0,0,0\");\n"
"\n"
"pref(\"javascript.enabled\",                  true);\n"
"pref(\"javascript.allow.mailnews\",           true);\n"
"pref(\"javascript.allow.signing\",            true);\n"
"pref(\"javascript.reflect_preferences\",      false);     // for PE\n"
"\n"
"pref(\"network.dnsAttempt\",              0);\n"
"pref(\"network.tcptimeout\",                  0);         // use default\n"
"pref(\"network.tcpbufsize\",                  0);         //\n"
"pref(\"network.use_async_dns\",               true);\n"
"pref(\"network.dnsCacheExpiration\",          900); // in seconds\n"
"pref(\"network.enableUrlMatch\",              true);\n"
"pref(\"network.max_connections\",             4);\n"
"pref(\"network.speed_over_ui\",               true);\n"
"pref(\"network.file_sort_method\",            0);     // NAME 0, TYPE 1, SIZE 2, DATE 3\n"
"pref(\"network.ftp.passive\",		    true);\n"
"pref(\"network.hosts.smtp_server\",           \"mail\");\n"
"pref(\"network.hosts.pop_server\",            \"mail\");\n"
"pref(\"network.hosts.nntp_server\",           \"news\");\n"
"pref(\"network.hosts.socks_server\",          \"\");\n"
"pref(\"network.hosts.socks_serverport\",      1080);\n"
"pref(\"network.hosts.socks_conf\",            \"\");\n"
"pref(\"network.proxy.autoconfig_url\",        \"\");\n"
"pref(\"network.proxy.type\",                  3); /* Changed default by req of Jon Kalb */\n"
"pref(\"network.proxy.ftp\",                   \"\");\n"
"pref(\"network.proxy.ftp_port\",              0);\n"
"pref(\"network.proxy.gopher\",                \"\");\n"
"pref(\"network.proxy.gopher_port\",           0);\n"
"pref(\"network.proxy.news\",                  \"\");\n"
"pref(\"network.proxy.news_port\",             0);\n"
"pref(\"network.proxy.http\",                  \"\");\n"
"pref(\"network.proxy.http_port\",             0);\n"
"pref(\"network.proxy.wais\",                  \"\");\n"
"pref(\"network.proxy.wais_port\",             0);\n"
"pref(\"network.proxy.ssl\",                   \"\");\n"
"pref(\"network.proxy.ssl_port\",              0);\n"
"pref(\"network.proxy.no_proxies_on\",         \"\");\n"
"pref(\"network.online\",                      true); //online/offline\n"
"pref(\"network.prompt_at_startup\",           false);//Ask me\n"
"pref(\"network.accept_cookies\",              0);     // 0 = Always, 1 = warn, 2 = never\n"
"pref(\"network.foreign_cookies\",             0); // 0 = Accept, 1 = Don't accept\n"
"pref(\"network.cookie.cookieBehavior\",       0); // 0-Accept, 1-dontAcceptForeign, 2-dontUse\n"
"pref(\"network.cookie.warnAboutCookies\",     false);\n"
"pref(\"network.signon.rememberSignons\",      true);\n"
"pref(\"network.cookie.filterName\",			\"\");\n"
"pref(\"network.sendRefererHeader\",           true);\n"
"pref(\"network.enablePad\",                   false); // Allow client to do proxy autodiscovery\n"
"pref(\"network.padPacURL\",                   \"\"); // The proxy autodiscovery url\n"
"pref(\"privacy.warn_no_policy\",              false); // Warn when submitting to site without policy\n"
"\n"
"pref(\"messages.new_window\",                 true); // ML obsolete; use mailnews.message_in_thread_window\n"
"pref(\"intl.accept_languages\",               \"en\");\n"
"pref(\"intl.mailcharset.cyrillic\",           \"koi8-r\");\n"
"pref(\"intl.accept_charsets\",                \"iso-8859-1,*,utf-8\");\n"
"pref(\"intl.auto_detect_encoding\",           true);\n"
"pref(\"intl.character_set\",                  2);     // CS_LATIN1\n"
"pref(\"intl.font_encoding\",                  6);     // CS_MAC_ROMAN\n"
"\n"
"pref(\"browser.enable_webfonts\",         true);\n"
"pref(\"browser.use_document_fonts\",              2); // 0 = never, 1 = quick, 2 = always\n"
"\n"
"// -- folders (Mac: these are binary aliases.)\n"
"localDefPref(\"browser.download_directory\",      \"\");\n"
"localDefPref(\"browser.cache.directory\",         \"\");\n"
"localDefPref(\"mail.signature_file\",             \"\");\n"
"localDefPref(\"mail.directory\",                  \"\");\n"
"localDefPref(\"mail.cc_file\",                    \"\");\n"
"localDefPref(\"news.cc_file\",                    \"\");\n"
"\n"
"pref(\"news.fancy_listing\",      true);      // obsolete\n"
"localDefPref(\"browser.cache.wfe.directory\", null);\n"
"pref(\"browser.wfe.show_value\", 1);\n"
"pref(\"browser.blink_allowed\", true);\n"
"pref(\"images.dither\", \"auto\");\n"
"pref(\"images.incremental_display\", true);\n"
"pref(\"network.wfe.use_async_dns\", true);\n"
"pref(\"network.wfe.tcp_connect_timeout\",0);\n"
"localDefPref(\"news.directory\",                  \"\");\n"
"localDefPref(\"security.directory\",              \"\");\n"
"\n"
"pref(\"autoupdate.enabled\",              true);\n"
"pref(\"autoupdate.confirm_install\",				false);\n"
"pref(\"autoupdate.background_download_enabled\",  true);\n"
"pref(\"autoupdate.background_download_directory\",  \"\");\n"
"pref(\"autoupdate.background_download_byte_range\",  3000);\n"
"pref(\"autoupdate.background_download_interval\",  10000);\n"
"pref(\"autoupdate.unsigned_jar_support\",  false);\n"
"\n"
"pref(\"imap.io.mac.logging\", false);\n"
"\n"
"pref(\"browser.editor.disabled\", false);\n"
"\n"
"pref(\"netcaster.containers.count\", \"2\");\n"
"pref(\"netcaster.containers.container1\", \"-3;'Channel_Finder';'http://netcaster.netscape.com/finder/container/index.html';1440;0\");\n"
"pref(\"netcaster.containers.container2\", \"1,2;'Channels';\");\n"
"pref(\"netcaster.channel.count\", \"0\");\n"
"pref(\"netcaster.castanet.count\", \"0\");\n"
"pref(\"netcaster.castanet.acceptCookies\", false);\n"
"pref(\"netcaster.castanet.loggingEnabled\", true);\n"
"pref(\"netcaster.castanet.profileEnabled\", true);\n"
"pref(\"netcaster.admin.startTime\", \"9\");\n"
"pref(\"netcaster.admin.endTime\", \"17\");\n"
"pref(\"netcaster.admin.times\", \"0\");\n"
"pref(\"netcaster.defaultChannel\", \"netscape_channel\");\n"
"\n"
"pref(\"SpellChecker.DefaultLanguage\", 0);\n"
"pref(\"SpellChecker.DefaultDialect\", 0);\n"
"\n"
"pref(\"li.enabled\", false);\n"
"pref(\"li.protocol\",\"ldap\");\n"
"\n"
"pref(\"li.client.bookmarks\", true);\n"
"pref(\"li.client.cookies\", true);\n"
"pref(\"li.client.filters\", true);\n"
"pref(\"li.client.addressbook\", true);\n"
"pref(\"li.client.globalhistory\", true);\n"
"pref(\"li.client.navcntr\", true);\n"
"pref(\"li.client.liprefs\", true);\n"
"pref(\"li.client.security\", true);\n"
"pref(\"li.client.javasecurity\", true);\n"
"\n"
"pref(\"li.client.news\", true);\n"
"pref(\"li.client.mail\", true);\n"
"\n"
"pref(\"li.login.name\", \"\");\n"
"pref(\"li.login.password\", \"\");\n"
"\n"
"pref(\"li.server.http.baseURL\", \"\");\n"
"pref(\"li.server.ldap.url\", \"\");\n"
"pref(\"li.server.ldap.userbase\", \"\");\n"
"\n"
"pref(\"li.sync.enabled\", false);\n"
"pref(\"li.sync.time\", 30);\n"
"\n"
"pref(\"mime.table.allow_add\", true);\n"
"pref(\"mime.table.allow_edit\", true);\n"
"pref(\"mime.table.allow_remove\", true);\n"
"/* -*- Mode: Java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-\n"
" *\n"
" * The contents of this file are subject to the Netscape Public License\n"
" * Version 1.0 (the \"NPL\"); you may not use this file except in\n"
" * compliance with the NPL.  You may obtain a copy of the NPL at\n"
" * http://www.mozilla.org/NPL/\n"
" *\n"
" * Software distributed under the NPL is distributed on an \"AS IS\" basis,\n"
" * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL\n"
" * for the specific language governing rights and limitations under the\n"
" * NPL.\n"
" *\n"
" * The Initial Developer of this code under the NPL is Netscape\n"
" * Communications Corporation.  Portions created by Netscape are\n"
" * Copyright (C) 1998 Netscape Communications Corporation.  All Rights\n"
" * Reserved.\n"
" */\n"
"\n"
"// Default configuration information for the client\n"
"//\n"
"\n"
"// config(\"startup.homepage_override_url\",\"http://home.netscape.com/home/first.html\");\n"
"config(\"autoadmin.append_emailaddr\",false);\n"
"config(\"autoadmin.failover_to_cached\",true);\n"
"\n"
"config(\"toolbar.logo.url\",\"http://home.netscape.com/\");\n"
"config(\"toolbar.logo.win_small_file\",\"\");\n"
"config(\"toolbar.logo.win_large_file\",\"\");\n"
"config(\"toolbar.logo.frames\",-1);\n"
"\n"
"config(\"toolbar.places.default_url\",\"http://guide.netscape.com\");\n"
"\n"
"config(\"toolbar.places.item_0.label\",\"The Internet\");\n"
"config(\"toolbar.places.item_0.url\",\"http://guide.netscape.com\");\n"
"config(\"toolbar.places.item_1.label\",\"People\");\n"
"config(\"toolbar.places.item_1.url\",\"http://guide.netscape.com/guide/people.html\");\n"
"config(\"toolbar.places.item_2.label\",\"Yellow Pages\");\n"
"config(\"toolbar.places.item_2.url\",\"http://guide.netscape.com/guide/yellow_pages.html\");\n"
"config(\"toolbar.places.item_3.label\",\"What's New\");\n"
"config(\"toolbar.places.item_3.url\",\"http://guide.netscape.com/guide/whats_new.html\");\n"
"config(\"toolbar.places.item_4.label\",\"What's Cool\");\n"
"config(\"toolbar.places.item_4.url\",\"http://guide.netscape.com/guide/whats_cool.html\");\n"
"\n"
"config(\"internal_url.net_search.url\",\"http://home.netscape.com/home/internet-search.html\");\n"
"config(\"internal_url.more_info_plugin.url\",\"http://cgi.netscape.com/eng/mozilla/2.0/extensions/info.cgi\");\n"
"config(\"internal_url.default_template.url\",\"http://home.netscape.com/home/gold3.0_templates.html\");\n"
"config(\"internal_url.page_from_wizard.url\", \"http://home.netscape.com/home/gold4.0_wizard.html\");\n"
"\n"
"config(\"menu.places.item_0.label\",\"The &Internet\");\n"
"config(\"menu.places.item_0.url\",\"http://guide.netscape.com\");\n"
"config(\"menu.places.item_1.label\",\"&People\");\n"
"config(\"menu.places.item_1.url\",\"http://guide.netscape.com/guide/people.html\");\n"
"config(\"menu.places.item_2.label\",\"&Yellow Pages\");\n"
"config(\"menu.places.item_2.url\",\"http://guide.netscape.com/guide/yellow_pages.html\");\n"
"config(\"menu.places.item_3.label\",\"What's &New\");\n"
"config(\"menu.places.item_3.url\",\"http://guide.netscape.com/guide/whats_new.html\");\n"
"config(\"menu.places.item_4.label\",\"What's &Cool\");\n"
"config(\"menu.places.item_4.url\",\"http://guide.netscape.com/guide/whats_cool.html\");\n"
"\n"
"config(\"menu.help.item_0.label\",\"&Help Contents\");\n"
"config(\"menu.help.item_0.url\",\"nethelp:netscape/home:start_here\");\n"
"config(\"menu.help.item_1.label\",\"&Release Notes\");\n"
"config(\"menu.help.item_1.url\",\"http://home.netscape.com/eng/mozilla/4.0/relnotes/windows-nav-4.0.html\");\n"
"config(\"menu.help.item_2.label\",\"&Product Information and Support\");\n"
"config(\"menu.help.item_2.url\",\"http://home.netscape.com/menu/prodsupp/client/\");\n"
"config(\"menu.help.item_3.label\",\"-\");\n"
"config(\"menu.help.item_4.label\",\"&Software Updates\");\n"
"config(\"menu.help.item_4.url\",\"http://home.netscape.com/home/update.html\");\n"
"config(\"menu.help.item_5.label\",\"Register No&w\");\n"
"config(\"menu.help.item_5.url\",\"http://home.netscape.com/home/register.html\");\n"
"config(\"menu.help.item_6.label\",\"&Member Services\");\n"
"config(\"menu.help.item_6.url\",\"http://home.netscape.com/home/services.html\");\n"
"config(\"menu.help.item_7.label\",\"-\");\n"
"config(\"menu.help.item_8.label\",\"&International Users\");\n"
"config(\"menu.help.item_8.url\",\"http://home.netscape.com/menu/intl/\");\n"
"config(\"menu.help.item_9.label\",\"S&ecurity\");\n"
"config(\"menu.help.item_9.url\",\"http://home.netscape.com/info/security-doc.html\");\n"
"config(\"menu.help.item_10.label\",\"-\");\n"
"config(\"menu.help.item_11.label\",\"Abou&t Plug-ins\");\n"
"config(\"menu.help.item_11.url\",\"about:plugins\");\n"
"config(\"menu.help.item_12.label\",\"About Font &Displayers\");\n"
"config(\"menu.help.item_12.url\",\"about:fonts\");\n"
"\n"
"config(\"personal_toolbar.item_0.label\",\"Internet\");\n"
"config(\"personal_toolbar.item_0.url\",\"http://guide.netscape.com/?t\");\n"
"config(\"personal_toolbar.item_1.label\",\"Lookup\");\n"
"config(\"personal_toolbar.item_1.url\",\"FOLDER\");\n"
"config(\"personal_toolbar.item_1.item_0.label\",\"People\");\n"
"config(\"personal_toolbar.item_1.item_0.url\",\"http://guide.netscape.com/guide/people.html?t\");\n"
"config(\"personal_toolbar.item_1.item_1.label\",\"Yellow Pages\");\n"
"config(\"personal_toolbar.item_1.item_1.url\",\"http://guide.netscape.com/guide/yellow_pages.html?t\");\n"
"config(\"personal_toolbar.item_2.label\",\"New&Cool\");\n"
"config(\"personal_toolbar.item_2.url\",\"FOLDER\");\n"
"config(\"personal_toolbar.item_2.item_0.label\",\"What's New\");\n"
"config(\"personal_toolbar.item_2.item_0.url\",\"http://guide.netscape.com/guide/whats_new.html?t\");\n"
"config(\"personal_toolbar.item_2.item_1.label\",\"What's Cool\");\n"
"config(\"personal_toolbar.item_2.item_1.url\",\"http://guide.netscape.com/guide/whats_cool.html?t\");\n"
"\n"
"config(\"personal_toolbar.CreateNewToolbar\", false);\n"
"config(\"personal_toolbar.NewToolbarFolderName\", \"\");\n"
"config(\"personal_toolbar.ToolbarFolderVersion\", \"\");\n"
"/* -*- Mode: Java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-\n"
" *\n"
" * The contents of this file are subject to the Netscape Public License\n"
" * Version 1.0 (the \"NPL\"); you may not use this file except in\n"
" * compliance with the NPL.  You may obtain a copy of the NPL at\n"
" * http://www.mozilla.org/NPL/\n"
" *\n"
" * Software distributed under the NPL is distributed on an \"AS IS\" basis,\n"
" * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the NPL\n"
" * for the specific language governing rights and limitations under the\n"
" * NPL.\n"
" *\n"
" * The Initial Developer of this code under the NPL is Netscape\n"
" * Communications Corporation.  Portions created by Netscape are\n"
" * Copyright (C) 1998 Netscape Communications Corporation.  All Rights\n"
" * Reserved.\n"
" */\n"
"\n"
"// The other platforms roll this all into \"toolbar mode\".\n"
"pref(\"browser.chrome.toolbar_tips\", true);\n"
"pref(\"browser.chrome.show_menubar\", true);\n"
"\n"
"pref(\"mail.empty_trash\", false);\n"
"\n"
"// Handled differently under Mac/Windows\n"
"pref(\"network.hosts.smtp_server\", \"localhost\");\n"
"pref(\"network.hosts.pop_server\", \"pop\");\n"
"pref(\"mail.check_new_mail\", true);\n"
"pref(\"mail.sort_by\", 0);\n"
"pref(\"news.sort_by\", 0);\n"
"pref(\"browser.startup.license_accepted\", \"\");\n"
"pref(\"browser.cache.memory_cache_size\", 3000);\n"
"pref(\"browser.cache.disk_cache_size\", 5000);\n"
"pref(\"mail.directory\", \"~/nsmail/\");\n"
"pref(\"mail.imap.root_dir\", \"~/ns_imap/\");\n"
"pref(\"mail.signature_file\", \"~/.signature\");\n"
"pref(\"mail.default_fcc\", \"~/nsmail/Sent\");\n"
"pref(\"news.directory\", \"~\");\n"
"pref(\"news.default_fcc\", \"~/nsmail/Sent\");\n"
"pref(\"mailnews.reply_on_top\", 0);\n"
"pref(\"mailnews.reply_with_extra_lines\", 0);\n"
"pref(\"browser.startup.default_window\", 0);\n"
"pref(\"security.warn_accept_cookie\", false);\n"
"pref(\"editor.disable_spell_checker\", false);\n"
"pref(\"editor.dont_lock_spell_files\", true);\n"
"\n"
"// Instead of \"delay_images\"\n"
"pref(\"browser.autoload_images\", true);\n"
"\n"
"// Unix only\n"
"pref(\"mail.use_movemail\", true);\n"
"pref(\"mail.use_builtin_movemail\", true);\n"
"pref(\"mail.movemail_program\", \"\");\n"
"pref(\"mail.movemail_warn\", false);\n"
"pref(\"mail.sash_geometry\", \"\");\n"
"pref(\"news.cache_xover\", false);\n"
"pref(\"news.show_first_unread\", false);\n"
"pref(\"news.sash_geometry\", \"\");\n"
"pref(\"helpers.global_mime_types_file\", \"/usr/local/lib/netscape/mime.types\");\n"
"pref(\"helpers.global_mailcap_file\", \"/usr/local/lib/netscape/mailcap\");\n"
"pref(\"helpers.private_mime_types_file\", \"~/.mime.types\");\n"
"pref(\"helpers.private_mailcap_file\", \"~/.mailcap\");\n"
"pref(\"applications.telnet\", \"xterm -e telnet %h %p\");\n"
"pref(\"applications.tn3270\", \"xterm -e tn3270 %h\");\n"
"pref(\"applications.rlogin\", \"xterm -e rlogin %h\");\n"
"pref(\"applications.rlogin_with_user\", \"xterm -e rlogin %h -l %u\");\n"
"pref(\"applications.tmp_dir\", \"/tmp\");\n"
"// On Solaris/IRIX, this should be \"lp\"\n"
"pref(\"print.print_command\", \"lpr\");\n"
"pref(\"print.print_reversed\", false);\n"
"pref(\"print.print_color\", true);\n"
"pref(\"print.print_landscape\", false);\n"
"pref(\"print.print_paper_size\", 0);\n"
"\n"
"// Not sure what this one does...\n"
"pref(\"browser.fancy_ftp\", true);\n"
"\n"
"// Fortezza stuff\n"
"pref(\"fortezza.toggle\", 1);\n"
"pref(\"fortezza.timeout\", 30);\n"
"\n"
"pref(\"intl.font_charset\", \"\");\n"
"pref(\"intl.font_spec_list\", \"\");\n"
"pref(\"mail.signature_date\", 0);\n"
"\n"
"// Outliner column defaults\n"
"pref(\"addressbook.searchpane.outliner_geometry\", \"\");\n"
"pref(\"addressbook.addresseepane.outliner_geometry\", \"\");\n"
"pref(\"addressbook.listpane.outliner_geometry\", \"\");\n"
"pref(\"addressbook.outliner_geometry\", \"\");\n"
"pref(\"mail.composition.addresspane.outliner_geometry\", \"\");\n"
"pref(\"bookmarks.outliner_geometry\", \"\");\n"
"pref(\"mail.categorypane.outliner_geometry\", \"\");\n"
"pref(\"mail.folderpane.outliner_geometry\", \"\");\n"
"pref(\"history.outliner_geometry\", \"\");\n"
"pref(\"mail.ldapsearchpane.outliner_geometry\", \"\");\n"
"pref(\"mail.searchpane.outliner_geometry\", \"\");\n"
"pref(\"mail.mailfilter.outliner_geometry\", \"\");\n"
"pref(\"preferences.lang.outliner_geometry\", \"\");\n"
"pref(\"preferences.dir.outliner_geometry\", \"\");\n"
"pref(\"preferences.font.outliner_geometry\", \"\");\n"
"pref(\"mail.subscribepane.all_groups.outliner_geometry\", \"\");\n"
"pref(\"mail.subscribepane.new_groups.outliner_geometry\", \"\");\n"
"pref(\"mail.subscribepane.search_groups.outliner_geometry\", \"\");\n"
"pref(\"mail.threadpane.outliner_geometry\", \"\");\n"
"pref(\"mail.threadpane.messagepane_height\", 400);\n"
"\n"
"// Customizable toolbar stuff\n"
"pref(\"custtoolbar.personal_toolbar_folder\", \"Personal Toolbar Folder\");\n"
"pref(\"custtoolbar.has_toolbar_folder\", true);\n"
"pref(\"custtoolbar.Browser.Navigation_Toolbar.position\", 0);\n"
"pref(\"custtoolbar.Browser.Navigation_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Browser.Navigation_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Browser.Location_Toolbar.position\", 1);\n"
"pref(\"custtoolbar.Browser.Location_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Browser.Location_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Browser.Personal_Toolbar.position\", 2);\n"
"pref(\"custtoolbar.Browser.Personal_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Browser.Personal_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Messenger.Navigation_Toolbar.position\", 0);\n"
"pref(\"custtoolbar.Messenger.Navigation_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Messenger.Navigation_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Messenger.Location_Toolbar.position\", 1);\n"
"pref(\"custtoolbar.Messenger.Location_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Messenger.Location_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Messages.Navigation_Toolbar.position\", 0);\n"
"pref(\"custtoolbar.Messages.Navigation_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Messages.Navigation_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Messages.Location_Toolbar.position\", 1);\n"
"pref(\"custtoolbar.Messages.Location_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Messages.Location_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Folders.Navigation_Toolbar.position\", 0);\n"
"pref(\"custtoolbar.Folders.Navigation_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Folders.Navigation_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Folders.Location_Toolbar.position\", 1);\n"
"pref(\"custtoolbar.Folders.Location_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Folders.Location_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Address_Book.Address_Book_Toolbar.position\", 0);\n"
"pref(\"custtoolbar.Address_Book.Address_Book_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Address_Book.Address_Book_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Compose_Message.Message_Toolbar.position\", 0);\n"
"pref(\"custtoolbar.Compose_Message.Message_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Compose_Message.Message_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Composer.Composition_Toolbar.position\", 0);\n"
"pref(\"custtoolbar.Composer.Composition_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Composer.Composition_Toolbar.open\", true);\n"
"pref(\"custtoolbar.Composer.Formatting_Toolbar.position\", 1);\n"
"pref(\"custtoolbar.Composer.Formatting_Toolbar.showing\", true);\n"
"pref(\"custtoolbar.Composer.Formatting_Toolbar.open\", true);\n"
"\n"
"pref(\"taskbar.x\", -1);\n"
"pref(\"taskbar.y\", -1);\n"
"pref(\"taskbar.floating\", false);\n"
"pref(\"taskbar.horizontal\", false);\n"
"pref(\"taskbar.ontop\", false);\n"
"pref(\"taskbar.button_style\", -1);\n"
"\n"
"config(\"menu.help.item_1.url\", \"http://home.netscape.com/eng/mozilla/5.0/relnotes/unix-5.0.html\");\n"
;
