# xpfe master makefile

build:
	@(cd appshell && $(MAKE))
	@(cd bootstrap && $(MAKE))
#	@(cd xpviewer && $(MAKE))

clean:
	@(cd appshell && $(MAKE) clean)
	@(cd bootstrap && $(MAKE) clean)
#	@(cd xpviewer && $(MAKE) clean)

